server.port=8083
spring.application.name=junction-service

# Eureka Discovery Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator Endpoints & Health Check Dashboard
management.endpoints.web.exposure.include=health,info,metrics,circuitbreakers,health
management.endpoint.health.show-details=always

# Resilience4j Circuit Breaker Configuration
resilience4j.circuitbreaker.instances.optimizerService.sliding-window-size=10
resilience4j.circuitbreaker.instances.optimizerService.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.optimizerService.wait-duration-in-open-state=10000ms
resilience4j.circuitbreaker.instances.optimizerService.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.optimizerService.automatic-transition-from-open-to-half-open-enabled=true

# Signal Timing Safety Guardrails (Seconds)
signalsync.timing.min-green=8
signalsync.timing.max-green=60
signalsync.timing.yellow=3
signalsync.timing.all-red=1.5
signalsync.timing.pedestrian-scramble-duration=15
signalsync.timing.default-fixed-green=20
