server.port=8084
spring.application.name=incident-service

# Eureka Discovery Client
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# Actuator Endpoints
management.endpoints.web.exposure.include=health,info,metrics

# Junction Service Integration Endpoint
signalsync.junction-service.url=http://localhost:8083/api/junctions
